name: Hello world
on:
   pull_request:

permissions:
   contents: write

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "[+] TEST_SECRET: ${{secrets.TEST_SECRET}}"
         echo "[+] user.login: ${{github.event.pull_request.user.login}}"
         echo "[+] github.actor: ${{github.actor}}"
         echo "[+] toJson: "
         echo "${{toJson(github)}}"
